last_change = 2026-09-09T16:16:01.735504Z
addr = 0x38e8d0
size = 0x132
name = "CLoopTypeClientServer_ActivateLoop"

[header]
name = "CLoopTypeClientServer_ActivateLoop"
addr = 0x38e8d0

[header.args]
