last_change = 2026-09-09T16:16:01.735555Z
addr = 0x3f81a0
size = 0x19
name = "CNetworkServerService_SetGameSpawnGroupMgr"

[header]
name = "CNetworkServerService_SetGameSpawnGroupMgr"
addr = 0x3f81a0

[header.args]
