last_change = 2026-09-09T16:16:01.735587Z
addr = 0x408250
size = 0xc9
name = "CNetworkServerService_GetServerSerializersCRC"

[header]
name = "CNetworkServerService_GetServerSerializersCRC"
addr = 0x408250

[header.args]
