last_change = 2026-09-09T16:16:01.735622Z
addr = 0x4299d0
size = 0x107
name = "CNetworkClientService_DisconnectGameNow"

[header]
name = "CNetworkClientService_DisconnectGameNow"
addr = 0x4299d0

[header.args]
