last_change = 2026-09-09T16:16:01.735665Z
addr = 0x48f730
size = 0x1a5
name = "Demo_PauseAtServerTick_CommandHandler"

[header]
name = "Demo_PauseAtServerTick_CommandHandler"
addr = 0x48f730

[header.args]
