last_change = 2026-09-09T16:16:01.735672Z
addr = 0x4ad060
size = 0x9e
name = "CNetworkGameClientBase_ProcessUpdateStringTable"

[header]
name = "CNetworkGameClientBase_ProcessUpdateStringTable"
addr = 0x4ad060

[header.args]
