last_change = 2026-09-09T16:16:01.735703Z
addr = 0x4cce60
size = 0x263
name = "CNetworkGameClientBase_StartChangeLevel"

[header]
name = "CNetworkGameClientBase_StartChangeLevel"
addr = 0x4cce60

[header.args]
