last_change = 2026-09-09T16:16:01.735696Z
addr = 0x4c7320
size = 0x450
name = "CNetworkGameClientBase_DisconnectGame"

[header]
name = "CNetworkGameClientBase_DisconnectGame"
addr = 0x4c7320

[header.args]
