last_change = 2026-09-09T16:16:01.735803Z
addr = 0x4fdc80
size = 0xf3c
name = "CNetworkGameServerBase_FillKV3ServerInfo"

[header]
name = "CNetworkGameServerBase_FillKV3ServerInfo"
addr = 0x4fdc80

[header.args]
