last_change = 2026-09-09T16:16:01.735820Z
addr = 0x5050c0
size = 0x2341
name = "CNetworkGameServerBase_ConnectClient"

[header]
name = "CNetworkGameServerBase_ConnectClient"
addr = 0x5050c0

[header.args]
