last_change = 2026-09-09T16:16:01.735833Z
addr = 0x50bde0
size = 0x48
name = "CNetworkGameServerBase_ServerPostSimulate"

[header]
name = "CNetworkGameServerBase_ServerPostSimulate"
addr = 0x50bde0

[header.args]
