last_change = 2026-09-09T16:16:01.735835Z
addr = 0x50cba0
size = 0x2a0
name = "CNetworkGameServerBase_ReserveServerForQueuedGame"

[header]
name = "CNetworkGameServerBase_ReserveServerForQueuedGame"
addr = 0x50cba0

[header.args]
