last_change = 2026-09-09T16:16:01.735981Z
addr = 0x517c40
size = 0xd1
name = "CEngineServer_SetFakeClientConVarValue"

[header]
name = "CEngineServer_SetFakeClientConVarValue"
addr = 0x517c40

[header.args]
