last_change = 2026-09-09T16:16:01.735926Z
addr = 0x514400
size = 0x17d
name = "CNetworkGameServer_PrepareForAssetLoad"

[header]
name = "CNetworkGameServer_PrepareForAssetLoad"
addr = 0x514400

[header.args]
