last_change = 2026-09-09T16:16:01.736061Z
addr = 0x5886f0
size = 0x54
name = "CInputService_IsClientOnlyCommandAllowed"

[header]
name = "CInputService_IsClientOnlyCommandAllowed"
addr = 0x5886f0

[header.args]
